"""Textos de la web en español (es) e inglés (en).

Para cambiar un texto, edítalo aquí en los dos idiomas. Las plantillas solo
leen estas claves; no hace falta tocar el HTML.
"""

EMAIL = "manumanusanroman@gmail.com"
LINKEDIN = "https://linkedin.com/in/manusanromanfdz"
RETOS_APP_URL = "https://sanromanu.pythonanywhere.com"

# Cuando tengas el vídeo de Retos de habilidad en YouTube, pega aquí el enlace
# de inserción (https://www.youtube.com/embed/XXXX). Vacío = la sección no se muestra.
RETOS_VIDEO_EMBED = ""

COUNTRIES = {
    "es": [
        {"people": "3,4 M", "name": "Uruguay", "fact": "2 Mundiales y 15 Copas América"},
        {"people": "3,9 M", "name": "Croacia", "fact": "Final del Mundial 2018; tercera en 1998 y 2022"},
        {"people": "5,9 M", "name": "Dinamarca", "fact": "Campeona de la Eurocopa 1992"},
        {"people": "5,6 M", "name": "Noruega", "fact": "Cuna de Haaland y Ødegaard"},
    ],
    "en": [
        {"people": "3.4M", "name": "Uruguay", "fact": "2 World Cups and 15 Copa América titles"},
        {"people": "3.9M", "name": "Croatia", "fact": "2018 World Cup final; third in 1998 and 2022"},
        {"people": "5.9M", "name": "Denmark", "fact": "Euro 1992 champions"},
        {"people": "5.6M", "name": "Norway", "fact": "Home of Haaland and Ødegaard"},
    ],
}

TEXT = {
    "es": {
        "lang_label": "Español",
        "nav": {
            "home": "Inicio",
            "about": "Sobre mí",
            "methodology": "Metodología",
            "projects": "Proyectos",
            "contact": "Contacto",
        },
        "menu": "Menú",
        "skip": "Saltar al contenido",
        "footer_rights": "© 2026 Manu Sanroman",
        "cta_title": "Lo que ves aquí es el porqué. El cómo lo cuento en persona.",
        "cta_button": "Hablemos",
        "meta": {
            "home": ("Manu Sanroman · Entrenador y metodología de fútbol formativo",
                     "Entrenador de fútbol formativo: desarrollo técnico del jugador, metodología por niveles y Retos de habilidad."),
            "about": ("Sobre mí · Manu Sanroman",
                      "Trayectoria, formación y certificaciones de Manu Sanroman, entrenador de fútbol formativo."),
            "methodology": ("Metodología · Manu Sanroman",
                            "Desarrollo por nivel y no por edad, con cuatro pilares: personal, individual, grupal y cultura futbolística."),
            "projects": ("Proyectos · Manu Sanroman", "Proyectos de desarrollo de jugadores creados por Manu Sanroman."),
            "retos": ("Retos de habilidad · Manu Sanroman",
                      "Un programa y una app para que el desarrollo técnico no termine al acabar el entrenamiento."),
            "contact": ("Contacto · Manu Sanroman", "Escríbeme para hablar de metodología, desarrollo de jugadores o colaboraciones."),
        },
        "home": {
            "kicker": "Entrenador · Desarrollo de jugadores · Metodología",
            "tagline": "Formo jugadores técnicos, creativos e imprevisibles.",
            "btn_methodology": "Ver metodología",
            "btn_cv": "Descargar CV",
            "photo_alt": "Manu Sanroman con la camiseta de Rayados",
            "path_title": "Trayectoria",
            "path": [
                "Fuerzas básicas de Rayados de Monterrey",
                "Real Madrid Graduate School · Máster en Big Data Deportivo",
                "Houston Dutch Lions FC",
            ],
            "countries_title": "No es cuestión de tamaño",
            "countries_sub": "Países con menos de 6 millones de habitantes que forman talento de élite.",
            "countries_nl": "Nuevo León tiene casi 6 millones.",
            "countries_close": "El talento está. Lo que cambia es cómo se forma.",
            "pillars_kicker": "Metodología",
            "pillars_title": "Por nivel, no por edad. Cuatro pilares.",
            "pillars_link": "Leer la metodología",
            "project_kicker": "Proyecto",
            "project_title": "Retos de habilidad",
            "project_text": "Retos semanales con gestos de jugadores históricos. El jugador entrena en casa, sube su vídeo y recibe feedback con criterios claros.",
            "project_button": "Ver proyecto",
            "project_alt": "Manu Sanroman haciendo toques con el balón",
        },
        "pillars": [
            {"name": "Personal", "who": "El jugador y el balón",
             "text": "El trabajo que nadie ve: en casa, antes o después de entrenar y los fines de semana. Aquí se acumulan las repeticiones que construyen la técnica."},
            {"name": "Individual", "who": "El jugador, el balón y el entrenador",
             "text": "Corrección y detalle. Información clara sobre qué hacer, cuándo y cómo, en la dificultad justa para aprender."},
            {"name": "Grupal", "who": "El jugador, sus compañeros y el entrenador",
             "text": "Donde la técnica se convierte en decisiones. Espacios reducidos, oposición progresiva y juego real."},
            {"name": "Cultura futbolística", "who": "El jugador y el fútbol",
             "text": "Ver fútbol, conocer a los grandes de la historia y entender por qué hacían lo que hacían. Quien conoce el juego reconoce más soluciones."},
        ],
        "methodology": {
            "kicker": "Metodología",
            "title": "Formar jugadores, no equipos de una temporada",
            "lead": "Mi metodología responde a una pregunta: ¿por qué países más pequeños que Nuevo León forman más talento?",
            "belgium_title": "El caso Bélgica",
            "belgium_text": "Con unos 11,7 millones no es un país pequeño, pero demuestra que la formación se puede cambiar. Tras la Eurocopa 2000 rehízo su modelo de formación y en 2015 llegó a ser nº 1 del ranking FIFA. He estudiado de cerca las academias del Anderlecht y del Club Brujas, y son parte de cómo construí mi metodología.",
            "principles_title": "Mis principios",
            "principles": [
                {"title": "Por nivel, no por edad.",
                 "text": "Un jugador no está listo porque cumpla años. Está listo cuando lo demuestra con el balón y en el juego. Si ya lo demostró, tiene que subir: un jugador sin reto deja de crecer."},
                {"title": "Primero el balón, después el sistema.",
                 "text": "Sin dominio técnico no hay táctica que funcione. Cuanto más joven o más novato, más contacto con el balón. La táctica llega cuando el jugador ya tiene personalidad con él."},
                {"title": "Lo que se repite mal, se aprende mal.",
                 "text": "Cada gesto técnico es un programa que el cerebro construye a base de repeticiones. Si la repetición es precisa, el gesto será fiable bajo presión. Si es tosca, no."},
                {"title": "Ver antes de decidir.",
                 "text": "Los mejores jugadores no ven más que los demás: saben qué mirar. La percepción y la anticipación también se entrenan."},
                {"title": "La creatividad se entrena.",
                 "text": "Nadie inventa de la nada. Los jugadores creativos copian, combinan y se atreven. Mi trabajo es darles referencias y la libertad para intentarlo."},
            ],
            "pillars_title": "Los cuatro pilares",
            "levels_title": "Cuatro niveles",
            "levels_col_level": "Nivel",
            "levels_col_game": "El partido",
            "levels": [("Nuevo", "3 vs 3"), ("Intermedio", "5 vs 5"), ("Alto", "9 vs 9"), ("Experto", "11 vs 11")],
            "levels_text": "A medida que el jugador sube, el trabajo individual deja paso al colectivo y el partido crece con él. Se sube de nivel cuando se demuestra, en la técnica y en el juego.",
            "practice_title": "En la práctica: Retos de habilidad",
            "practice_text": "Un programa que creé para que el desarrollo no termine al acabar el entrenamiento: gestos de jugadores históricos, vídeos semanales desde casa y feedback con criterios claros.",
            "practice_link": "Ver proyecto",
        },
        "about": {
            "kicker": "Sobre mí",
            "title": "Manu Sanroman",
            "intro": [
                "Entrenador de fútbol formativo. Jugué en México (Cruz Azul Sub-11), Estados Unidos (Texas Rush) y España (campus de Mareo, Sporting de Gijón), así que conozco tres formas distintas de entender el fútbol.",
                "Entreno desde los 15 años. En Houston Dutch Lions entrené a jugadores de 4 a 18 años, aporté a la metodología del club (espacios reducidos y progresión con balón) y puse en marcha su programa de entrenamiento individual. Llevo tres temporadas en las fuerzas básicas de Rayados con la categoría Sub-10.",
                "Creé los Retos de habilidad para que el jugador siga mejorando su técnica en casa. Tengo un máster en Big Data Deportivo por Real Madrid Graduate School y trabajo en español e inglés.",
                "Busco ser metodólogo de una cantera: decidir qué se entrena, cuándo y por qué.",
            ],
            "photo_alt": "Cuerpo técnico de Rayados en el Estadio BBVA",
            "experience_title": "Experiencia",
            "experience": [
                {"role": "Entrenador Sub-10", "org": "Rayados de Monterrey · Fuerzas básicas (Rayados en la Mira)",
                 "when": "Ago 2023 – Actualidad", "where": "Monterrey, México",
                 "points": [
                     "Tercera temporada consecutiva al frente del grupo Sub-10.",
                     "Creador de los Retos de habilidad, con su propia aplicación web.",
                 ]},
                {"role": "Entrenador y becario de Operaciones", "org": "Houston Dutch Lions FC",
                 "when": "Ago 2021 – Dic 2022", "where": "Houston / The Woodlands, EE. UU.",
                 "points": [
                     "Sesiones para equipos de 4 a 18 años.",
                     "Contribuí a la metodología del club: espacios reducidos y progresión con balón.",
                     "Puse en marcha el programa de entrenamiento individual.",
                 ]},
                {"role": "Entrenador de desarrollo individual", "org": "Tiempo parcial",
                 "when": "2011 – 2021", "where": "Estados Unidos",
                 "points": ["Sesiones técnicas individuales con feedback en vídeo."]},
            ],
            "education_title": "Formación",
            "education": [
                {"title": "Máster de Formación Permanente en Big Data Deportivo",
                 "org": "Real Madrid Graduate School – Universidad Europea", "when": "2026"},
                {"title": "B.S. Sports Business Administration",
                 "org": "Stephen F. Austin State University", "when": "2019 – 2023"},
            ],
            "certs_title": "Licencias y certificaciones",
            "certs": [
                "Licencias Grassroots de U.S. Soccer: 4v4, 7v7, 9v9 y 11v11",
                "Especialista en Scouting y Análisis del Juego · Coaches' Voice School",
                "Metodología del Fútbol · MBP School of Coaches",
                "Google Analytics",
            ],
            "languages_title": "Idiomas",
            "languages": "Español (nativo) · Inglés (fluido)",
            "cv_button": "Descargar CV (PDF)",
        },
        "projects": {
            "kicker": "Proyectos",
            "title": "Lo que he construido",
            "lead": "Herramientas y programas que nacen de una necesidad real del campo.",
            "entries": [
                {"key": "retos", "title": "Retos de habilidad",
                 "text": "Un programa y una app para entrenar la técnica en casa con gestos de jugadores históricos."},
            ],
            "more": "Ver proyecto",
        },
        "retos": {
            "kicker": "Proyecto",
            "title": "Retos de habilidad",
            "lead": "Un programa y una app para que el desarrollo técnico no termine al acabar el entrenamiento.",
            "problem_title": "El problema",
            "problem": "El jugador entrena con su equipo unos días a la semana. El resto del tiempo, nadie trabaja su técnica, y la técnica se construye con miles de repeticiones.",
            "idea_title": "La idea",
            "idea": "Retos semanales con gestos de jugadores históricos. El jugador entrena en casa (el pilar Personal de mi metodología) y, de paso, conoce la historia del fútbol.",
            "steps_title": "Cómo funciona",
            "steps": [
                ("El reto", "Cada semana, un gesto técnico de un jugador histórico, con su explicación."),
                ("El vídeo", "El jugador lo entrena en casa, se graba y sube su vídeo a la app."),
                ("El feedback", "El entrenador lo evalúa con criterios definidos y le dice cómo mejorar."),
            ],
            "built_title": "Lo que construí",
            "built": [
                "Registro de padres y tutores",
                "Acceso para el cuerpo técnico",
                "Subida de vídeos y retos semanales",
                "Feedback con criterios definidos",
            ],
            "built_note": "Diseñada y desarrollada por mí.",
            "facts_title": "En números",
            "facts": [("~15", "jugadores en la edición actual"), ("Sep 2026", "inicio de la edición actual"), ("100 %", "idea propia")],
            "video_title": "Recorrido por la app",
            "app_button": "Abrir la app",
        },
        "contact": {
            "kicker": "Contacto",
            "title": "Hablemos",
            "lead": "Si buscas a alguien para el desarrollo de jugadores o la metodología de tu academia, escríbeme.",
            "email_label": "Email",
            "linkedin_label": "LinkedIn",
            "name": "Nombre",
            "email": "Email",
            "org": "Club u organización (opcional)",
            "message": "Mensaje",
            "send": "Enviar mensaje",
            "sent": "¡Gracias! Tu mensaje ha llegado. Te respondo pronto.",
            "error": "No se pudo enviar el mensaje. Escríbeme directamente a",
            "invalid": "Revisa los campos: nombre, un email válido y un mensaje.",
        },
        "not_found": "Esta página no existe.",
        "back_home": "Volver al inicio",
    },
    "en": {
        "lang_label": "English",
        "nav": {
            "home": "Home",
            "about": "About",
            "methodology": "Methodology",
            "projects": "Projects",
            "contact": "Contact",
        },
        "menu": "Menu",
        "skip": "Skip to content",
        "footer_rights": "© 2026 Manu Sanroman",
        "cta_title": "What you see here is the why. The how, I share in person.",
        "cta_button": "Let's talk",
        "meta": {
            "home": ("Manu Sanroman · Youth football coach and methodology",
                     "Youth football coach: technical player development, a level-based methodology and the Skills Challenge."),
            "about": ("About · Manu Sanroman",
                      "Experience, education and certifications of Manu Sanroman, youth football coach."),
            "methodology": ("Methodology · Manu Sanroman",
                            "Development by level, not age, built on four pillars: personal, individual, group and football culture."),
            "projects": ("Projects · Manu Sanroman", "Player development projects created by Manu Sanroman."),
            "retos": ("Skills Challenge · Manu Sanroman",
                      "A programme and an app so technical development doesn't stop when training ends."),
            "contact": ("Contact · Manu Sanroman", "Get in touch about methodology, player development or collaborations."),
        },
        "home": {
            "kicker": "Coach · Player Development · Methodology",
            "tagline": "I develop technical, creative and unpredictable players.",
            "btn_methodology": "See the methodology",
            "btn_cv": "Download CV",
            "photo_alt": "Manu Sanroman wearing a Rayados shirt",
            "path_title": "Path",
            "path": [
                "CF Monterrey (Rayados) academy",
                "Real Madrid Graduate School · Master's in Sports Big Data",
                "Houston Dutch Lions FC",
            ],
            "countries_title": "Size isn't the reason",
            "countries_sub": "Countries with fewer than 6 million people that produce elite talent.",
            "countries_nl": "Nuevo León has almost 6 million.",
            "countries_close": "The talent is there. What changes is how it's developed.",
            "pillars_kicker": "Methodology",
            "pillars_title": "Level, not age. Four pillars.",
            "pillars_link": "Read the methodology",
            "project_kicker": "Project",
            "project_title": "Skills Challenge",
            "project_text": "Weekly challenges built on skills of historic players. Players train at home, upload their video and get feedback against clear criteria.",
            "project_button": "See project",
            "project_alt": "Manu Sanroman juggling a ball",
        },
        "pillars": [
            {"name": "Personal", "who": "The player and the ball",
             "text": "The work nobody sees: at home, before or after training, on weekends. This is where the repetitions that build technique add up."},
            {"name": "Individual", "who": "The player, the ball and the coach",
             "text": "Correction and detail. Clear information on what to do, when and how, at exactly the right difficulty to learn."},
            {"name": "Group", "who": "The player, teammates and the coach",
             "text": "Where technique becomes decisions. Small spaces, progressive opposition and real play."},
            {"name": "Football culture", "who": "The player and the game",
             "text": "Watching football, knowing the greats and understanding why they did what they did. A player who knows the game recognises more solutions."},
        ],
        "methodology": {
            "kicker": "Methodology",
            "title": "Developing players, not one-season teams",
            "lead": "My methodology answers one question: why do countries smaller than Nuevo León produce more talent?",
            "belgium_title": "The Belgian case",
            "belgium_text": "With around 11.7 million people it isn't a small country, but it proves development can be changed. After Euro 2000 it rebuilt its youth model, and by 2015 it was FIFA's number one. I have studied the Anderlecht and Club Brugge academies closely, and they are part of how I built my methodology.",
            "principles_title": "My principles",
            "principles": [
                {"title": "Level, not age.",
                 "text": "A player isn't ready because of a birthday. They're ready when they prove it, with the ball and in the game. Once they've proved it, they must move up: a player without a challenge stops growing."},
                {"title": "Ball first, system second.",
                 "text": "Without technical mastery, no tactic works. The younger or newer the player, the more ball contact. Tactics come once the player has personality on the ball."},
                {"title": "Practise it badly, learn it badly.",
                 "text": "Every technical action is a program the brain builds through repetition. Precise repetition makes it reliable under pressure. Sloppy repetition doesn't."},
                {"title": "See before you decide.",
                 "text": "The best players don't see more than everyone else: they know what to look at. Perception and anticipation can be trained too."},
                {"title": "Creativity can be trained.",
                 "text": "Nobody invents from nothing. Creative players copy, combine and dare. My job is to give them references and the freedom to try."},
            ],
            "pillars_title": "The four pillars",
            "levels_title": "Four levels",
            "levels_col_level": "Level",
            "levels_col_game": "The game",
            "levels": [("Beginner", "3v3"), ("Intermediate", "5v5"), ("Advanced", "9v9"), ("Expert", "11v11")],
            "levels_text": "As players move up, individual work gives way to team play and the game grows with them. You move up when you prove it, in technique and in the game.",
            "practice_title": "In practice: Skills Challenge",
            "practice_text": "A programme I created so development doesn't stop when training ends: skills from historic players, weekly videos from home and feedback against clear criteria.",
            "practice_link": "See project",
        },
        "about": {
            "kicker": "About",
            "title": "Manu Sanroman",
            "intro": [
                "Youth football coach. I played in Mexico (Cruz Azul U-11), the United States (Texas Rush) and Spain (Mareo camps, Sporting de Gijón), so I know three different ways of understanding football.",
                "I've coached since I was 15. At Houston Dutch Lions I coached players aged 4 to 18, contributed to the club's methodology (small spaces and ball progression) and launched its individual training programme. I'm in my third season in the Rayados academy with the U-10 group.",
                "I created the Skills Challenge so players keep improving their technique at home. I hold a Master's in Sports Big Data from Real Madrid Graduate School and work in Spanish and English.",
                "My next step is Head of Methodology at an academy: deciding what is trained, when and why.",
            ],
            "photo_alt": "Rayados coaching staff at Estadio BBVA",
            "experience_title": "Experience",
            "experience": [
                {"role": "U-10 Coach", "org": "Rayados de Monterrey · Academy (Rayados en la Mira)",
                 "when": "Aug 2023 – Present", "where": "Monterrey, Mexico",
                 "points": [
                     "Third consecutive season leading the U-10 group.",
                     "Creator of the Skills Challenge and its web app.",
                 ]},
                {"role": "Soccer Coach & Operations Intern", "org": "Houston Dutch Lions FC",
                 "when": "Aug 2021 – Dec 2022", "where": "Houston / The Woodlands, USA",
                 "points": [
                     "Sessions for teams aged 4 to 18.",
                     "Contributed to the club's methodology: small-sided spaces and ball progression.",
                     "Launched the individual training programme.",
                 ]},
                {"role": "Private Development Coach", "org": "Part-time",
                 "when": "2011 – 2021", "where": "United States",
                 "points": ["Individual technical sessions with video feedback."]},
            ],
            "education_title": "Education",
            "education": [
                {"title": "Master's (Continuing Education) in Sports Big Data",
                 "org": "Real Madrid Graduate School – Universidad Europea", "when": "2026"},
                {"title": "B.S. Sports Business Administration",
                 "org": "Stephen F. Austin State University", "when": "2019 – 2023"},
            ],
            "certs_title": "Licences & certifications",
            "certs": [
                "U.S. Soccer Grassroots Licenses: 4v4, 7v7, 9v9 and 11v11",
                "Specialist in Scouting & Game Analysis · Coaches' Voice School",
                "Football Methodology · MBP School of Coaches",
                "Google Analytics",
            ],
            "languages_title": "Languages",
            "languages": "Spanish (native) · English (fluent)",
            "cv_button": "Download CV (PDF)",
        },
        "projects": {
            "kicker": "Projects",
            "title": "What I've built",
            "lead": "Tools and programmes born from a real need on the pitch.",
            "entries": [
                {"key": "retos", "title": "Skills Challenge",
                 "text": "A programme and an app to train technique at home with skills from historic players."},
            ],
            "more": "See project",
        },
        "retos": {
            "kicker": "Project",
            "title": "Skills Challenge",
            "lead": "A programme and an app so technical development doesn't stop when training ends.",
            "problem_title": "The problem",
            "problem": "Players train with their team a few days a week. The rest of the time nobody works on their technique, and technique is built through thousands of repetitions.",
            "idea_title": "The idea",
            "idea": "Weekly challenges built on skills of historic players. Players train at home (the Personal pillar of my methodology) and learn football history along the way.",
            "steps_title": "How it works",
            "steps": [
                ("The challenge", "Each week, a skill from a historic player, with its explanation."),
                ("The video", "The player practises at home, films it and uploads the video to the app."),
                ("The feedback", "The coach assesses it against defined criteria and explains how to improve."),
            ],
            "built_title": "What I built",
            "built": [
                "Parent and guardian registration",
                "Access for coaching staff",
                "Video uploads and weekly challenges",
                "Feedback against defined criteria",
            ],
            "built_note": "Designed and developed by me.",
            "facts_title": "In numbers",
            "facts": [("~15", "players in the current edition"), ("Sep 2026", "start of the current edition"), ("100%", "my own idea")],
            "video_title": "App walkthrough",
            "app_button": "Open the app",
        },
        "contact": {
            "kicker": "Contact",
            "title": "Let's talk",
            "lead": "If you're looking for someone to lead player development or your academy's methodology, write to me.",
            "email_label": "Email",
            "linkedin_label": "LinkedIn",
            "name": "Name",
            "email": "Email",
            "org": "Club or organisation (optional)",
            "message": "Message",
            "send": "Send message",
            "sent": "Thank you! Your message has arrived. I'll reply soon.",
            "error": "The message couldn't be sent. Write to me directly at",
            "invalid": "Please check the fields: name, a valid email and a message.",
        },
        "not_found": "This page doesn't exist.",
        "back_home": "Back to home",
    },
}
